## src/application.toml - 聊天通信客户端 web版 by sveltekit
## 2026-01-02 05:30:10



## App 应用识别铭牌
[app]
name = "IM_Clent_2026"
name_zh = "即时通讯客户端_2026"
name_kr = ""
name_jp = ""
name_tal = ""
version = "0.1.0"


## 管理端接口
[manger_center]
host = "https://api2.xx.com:8080/appapi/"
singeut = "a0026e6a605015688a6df96fead"
app_id = "10008800"
app_key = "123456"


## 兜底 - 聊天服务器
[base_im]
host = "https://im.xx.com:8080/ws/"
singeut = "a0026e6a605015688a6df96fead"
app_id = "10008800"
app_key = "123456"


## 兜底 - Api服务器
[base_api]
host = "https://api4.xx.com:8080/v1/"
singeut = "a0026e6a605015688a6df96fead"
app_id = "10008800"
app_key = "123456"


## 兜底服务器接口
[base_payment]
host = "https://payment.xx.com:8080/appapi/"
singeut = "a0026e6a605015688a6df96fead"
app_id = "10008800"
app_key = "123456"


